-- ============================================================
-- Mon Names Converter — Seed data from data/names.csv
-- Auto-generated by scripts/csv-to-sql.js — do not edit manually.
-- To update: edit data/names.csv, re-run the script, then migrate.
-- ============================================================

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('နာင်ဗြာ', 'နောင်ကြာ', 'Naing Kyar', 'Future brightness; long-lasting glory', 'male', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Naing Kya', 'english'
FROM names WHERE mon = 'နာင်ဗြာ' AND english = 'Naing Kyar';

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Naing Kyar', 'english'
FROM names WHERE mon = 'နာင်ဗြာ' AND english = 'Naing Kyar';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('မတ်ထဝ်', 'မသိုး', 'Ma Thoe', 'Shining one; luminous', 'female', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Ma Toe', 'english'
FROM names WHERE mon = 'မတ်ထဝ်' AND english = 'Ma Thoe';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('မိဥ်ꩫ်', 'မင်းသည်', 'Min Thi', 'Royalty; nobility of character', 'male', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Min Thi', 'english'
FROM names WHERE mon = 'မိဥ်ꩫ်' AND english = 'Min Thi';

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Min Ti', 'english'
FROM names WHERE mon = 'မိဥ်ꩫ်' AND english = 'Min Thi';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('ဍုင်', 'မြို့', 'Dung', 'City; homeland; place of origin', 'neutral', 1);

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('ဗြဲ', 'ကြယ်', 'Hkre', 'Star; celestial light', 'neutral', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Kre', 'english'
FROM names WHERE mon = 'ဗြဲ' AND english = 'Hkre';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('မိစိုတ်', 'မသက်', 'Mi Sot', 'Living; full of life and vitality', 'female', 1);

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('နာင်ꩦ်', 'နောင်ထွတ်', 'Naing Htut', 'Future peak; rising high', 'male', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Naing Htoot', 'english'
FROM names WHERE mon = 'နာင်ꩦ်' AND english = 'Naing Htut';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('ဒြဲ', 'ကြဲ', 'Hkre', 'Brave; courageous spirit', 'male', 1);
