-- ============================================================
-- Mon Names Converter — Seed data from data/names.csv
-- Auto-generated by scripts/csv-to-sql.js — do not edit manually.
-- To update: edit data/names.csv, re-run the script, then migrate.
-- ============================================================

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('နာင်ဗြာ', 'နောင်ကြာ', 'Naing Kyar', 'Future brightness; long-lasting glory', 'male', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Naing Kya', 'english'
FROM names WHERE mon = 'နာင်ဗြာ' AND english = 'Naing Kyar';

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Naing Kyar', 'english'
FROM names WHERE mon = 'နာင်ဗြာ' AND english = 'Naing Kyar';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('မတ်ထဝ်', 'မသိုး', 'Ma Thoe', 'Shining one; luminous', 'female', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Ma Toe', 'english'
FROM names WHERE mon = 'မတ်ထဝ်' AND english = 'Ma Thoe';

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Moot Taw', 'english'
FROM names WHERE mon = 'မတ်ထဝ်' AND english = 'Ma Thoe';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('မိဥ်ꩫ်', 'မင်းသည်', 'Min Thi', 'Royalty; nobility of character', 'male', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Min Ti', 'english'
FROM names WHERE mon = 'မိဥ်ꩫ်' AND english = 'Min Thi';

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Min Thit', 'english'
FROM names WHERE mon = 'မိဥ်ꩫ်' AND english = 'Min Thi';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('ဍုင်', 'မြို့', 'Dung', 'City; homeland; place of origin', 'neutral', 1);

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('ဗြဲ', 'ကြယ်', 'Hkre', 'Star; celestial light', 'neutral', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Kre', 'english'
FROM names WHERE mon = 'ဗြဲ' AND english = 'Hkre';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('မိစိုတ်', 'မသက်', 'Mi Sot', 'Living; full of life and vitality', 'female', 1);

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('နာင်ꩦ်', 'နောင်ထွတ်', 'Naing Htut', 'Future peak; rising high', 'male', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Naing Htoot', 'english'
FROM names WHERE mon = 'နာင်ꩦ်' AND english = 'Naing Htut';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('ဒြဲ', 'ကြဲ', 'Dre', 'Brave; courageous spirit', 'male', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Hkre', 'english'
FROM names WHERE mon = 'ဒြဲ' AND english = 'Dre';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('မိမိ', 'မေမေ', 'Mi Mi', 'Beloved; dear one; affectionate address', 'female', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Mee Mee', 'english'
FROM names WHERE mon = 'မိမိ' AND english = 'Mi Mi';

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Mi Mi', 'english'
FROM names WHERE mon = 'မိမိ' AND english = 'Mi Mi';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('ဍာ်မိ', 'ကြည်မေ', 'Dah Mi', 'Clear as water; pure and bright', 'female', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Da Mi', 'english'
FROM names WHERE mon = 'ဍာ်မိ' AND english = 'Dah Mi';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('နာင်ဍာ်', 'နောင်ရေ', 'Naing Da', 'Calm and deep as water; future flow', 'male', 1);

INSERT OR IGNORE INTO aliases (name_id, alias, language)
SELECT id, 'Naing Dar', 'english'
FROM names WHERE mon = 'နာင်ဍာ်' AND english = 'Naing Da';

INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)
VALUES ('မတ်ဗြာ', 'မဆောင်း', 'Mat Bra', 'Glorious bearer; one who carries light', 'female', 0);
