#!/usr/bin/env node
/**
 * csv-to-sql.js
 * =============
 * Reads data/names.csv and writes migrations/0004_seed_names.sql.
 *
 * CSV columns (header row required):
 *   mon        — name in Mon script              (required)
 *   burmese    — name in Burmese/Myanmar script  (optional)
 *   english    — romanised / English spelling     (optional)
 *   meaning    — meaning, usage notes             (optional)
 *   gender     — male | female | neutral          (defaults to neutral)
 *   verified   — 1 | 0                            (defaults to 1)
 *   aliases    — pipe-separated alias:language pairs, e.g.
 *                "Naing Kya:english|Naing Kyar:english"  (optional)
 *
 * To add names: edit data/names.csv, then run:
 *   node scripts/csv-to-sql.js
 *   npm run db:migrate:local   (or db:migrate:remote for production)
 */

const fs   = require('fs');
const path = require('path');

const CSV_PATH = path.join(__dirname, '../data/names.csv');
const OUT_PATH = path.join(__dirname, '../migrations/0004_seed_names.sql');

// ── CSV parser ────────────────────────────────────────────────────────────────
// Handles quoted fields (including fields with commas/newlines inside quotes).
function parseCSV(text) {
  const lines = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
  const rows  = [];

  for (const line of lines) {
    if (!line.trim()) continue;

    const fields = [];
    let field    = '';
    let inQuotes = false;

    for (let i = 0; i < line.length; i++) {
      const ch   = line[i];
      const next = line[i + 1];

      if (inQuotes) {
        if (ch === '"' && next === '"') { field += '"'; i++; }  // escaped quote
        else if (ch === '"')            { inQuotes = false; }
        else                            { field += ch; }
      } else {
        if (ch === '"')       { inQuotes = true; }
        else if (ch === ',')  { fields.push(field); field = ''; }
        else                  { field += ch; }
      }
    }
    fields.push(field);
    rows.push(fields);
  }

  return rows;
}

// ── SQL escaping ──────────────────────────────────────────────────────────────
const sqlStr = v =>
  v === '' || v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;

// ── Main ──────────────────────────────────────────────────────────────────────
const raw  = fs.readFileSync(CSV_PATH, 'utf8');
const rows = parseCSV(raw);

if (rows.length < 2) {
  console.error('CSV has no data rows.');
  process.exit(1);
}

const VALID_GENDERS   = new Set(['male', 'female', 'neutral']);
const VALID_LANGUAGES = new Set(['mon', 'burmese', 'english']);

// Map header names to column indices
const header = rows[0].map(h => h.trim().toLowerCase());
const col    = name => {
  const i = header.indexOf(name);
  if (i === -1) throw new Error(`CSV is missing required column: "${name}"`);
  return i;
};

const iMon      = col('mon');
const iBurmese  = col('burmese');
const iEnglish  = col('english');
const iMeaning  = col('meaning');
const iGender   = col('gender');
const iVerified = col('verified');
const iAliases  = col('aliases');

const lines = [
  `-- ============================================================`,
  `-- Mon Names Converter — Seed data from data/names.csv`,
  `-- Auto-generated by scripts/csv-to-sql.js — do not edit manually.`,
  `-- To update: edit data/names.csv, re-run the script, then migrate.`,
  `-- ============================================================`,
  ``,
];

let nameCount  = 0;
let aliasCount = 0;
let skipped    = 0;

for (let i = 1; i < rows.length; i++) {
  const row = rows[i];
  const get = idx => (row[idx] || '').trim();

  const mon     = get(iMon);
  const burmese = get(iBurmese);
  const english = get(iEnglish);
  const meaning = get(iMeaning);
  const rawGend = get(iGender).toLowerCase();
  const gender  = VALID_GENDERS.has(rawGend) ? rawGend : 'neutral';
  const verified = get(iVerified) === '0' ? 0 : 1;
  const aliasRaw = get(iAliases);

  if (!mon) { skipped++; continue; }  // mon is the only required field

  // INSERT the name; skip if (mon, english) pair already exists.
  lines.push(
    `INSERT OR IGNORE INTO names (mon, burmese, english, meaning, gender, verified)`,
    `VALUES (${sqlStr(mon)}, ${sqlStr(burmese)}, ${sqlStr(english)}, ` +
           `${sqlStr(meaning)}, '${gender}', ${verified});`,
    ``,
  );
  nameCount++;

  // INSERT aliases using a subquery to find the parent name_id.
  if (aliasRaw) {
    for (const part of aliasRaw.split('|')) {
      const colonIdx = part.lastIndexOf(':');
      if (colonIdx === -1) continue;
      const alias    = part.slice(0, colonIdx).trim();
      const language = part.slice(colonIdx + 1).trim().toLowerCase();
      if (!alias || !VALID_LANGUAGES.has(language)) continue;

      lines.push(
        `INSERT OR IGNORE INTO aliases (name_id, alias, language)`,
        `SELECT id, ${sqlStr(alias)}, '${language}'`,
        `FROM names WHERE mon = ${sqlStr(mon)} AND english = ${sqlStr(english)};`,
        ``,
      );
      aliasCount++;
    }
  }
}

fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');

console.log(`Generated ${OUT_PATH}`);
console.log(`  ${nameCount} name(s), ${aliasCount} alias(es)` +
            (skipped ? `, ${skipped} row(s) skipped (missing mon)` : ''));
console.log('');
console.log('Apply locally:   npm run db:migrate:local');
console.log('Apply remotely:  npm run db:migrate:remote');
